---

- hosts: all
  become: true
  pre_tasks:

  - name: updates repo cache (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution  == "CentOS"

  - name: updates repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


  - hosts: all
    become: true
    roles:
      - base

  - hosts: web_servers
    become: true
    roles:
      - web_servers

  - hosts: db_servers
    become: true
    roles:
      - db_servers



